FROM argnctu/ros-caffe-ssd

WORKDIR $HOME/data
RUN wget http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar && \
    wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar && \
    wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar && \
    tar -xvf VOCtrainval_11-May-2012.tar && \
    tar -xvf VOCtrainval_06-Nov-2007.tar && \
    tar -xvf VOCtest_06-Nov-2007.tar 

WORKDIR $CAFFE_ROOT/models/VGGNet
RUN wget http://cs.unc.edu/~wliu/projects/ParseNet/VGG_ILSVRC_16_layers_fc_reduced.caffemodel 

WORKDIR $CAFFE_ROOT
RUN ./data/VOC0712/create_list.sh && \
    ./data/VOC0712/create_data.sh

COPY ssd_pascal.py examples/ssd/ssd_pascal.py


